# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0983b6ee61cac4cc2810b0f20895035e0c0b39afa4ebe22855bbe95c71105524d0f53512994574df5ef66b7918e75e7fea2a59f7f7cea5a394dff67a93997577

test:
  secret_key_base: 66e57dc06e35242f224d6277dd7fd082138162d7af17e7e5dbdff16a673863b1f313f68fe4d0677bfea9e7d4d56fc2b5e7fd2577038e90679e3fd21514255124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
